schema_version = "1.0.0"

id = "engon"
version = "1.5.1"
name = "engon"
tagline = "Browse assets, filter and sort, scatter, animate, adjust rigs"
maintainer = "polygoniq <ahoy@polygoniq.com>"
type = "add-on"

website = "https://docs.polygoniq.com/engon/1.4.1/"
tags = ["Add Mesh", "Animation", "Material", "Mesh", "Object", "Scene", "User Interface"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2018- polygoniq xyz s.r.o",
]

[permissions]
network = "Update functionality for older Blender versions"
files = "Install asset packs, load assets, store logs and state"